args <- commandArgs(trailingOnly=TRUE)
stopifnot(length(args)==2)
root <- normalizePath(args[1]); dest <- normalizePath(args[2])
.libPaths(c(file.path(dirname(root),'ppmi-deseq2-2026-09-12','R-library'),.libPaths()))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(jsonlite))
started <- Sys.time()
meta <- read.delim(file.path(dest,'metadata.tsv'),colClasses=c(PATNO='character'))
plan <- fromJSON(file.path(dest,'input.json'))
genes <- readLines(file.path(root,'gene_ids.txt'))
stopifnot(identical(meta$PATNO,plan$training_PATNO),!anyDuplicated(meta$PATNO))
con <- file(file.path(dest,'counts.int32'),'rb')
v <- readBin(con,integer(),n=length(genes)*nrow(meta),size=4,endian='little');close(con)
stopifnot(length(v)==length(genes)*nrow(meta),all(v>=0))
cts <- matrix(v,nrow=length(genes),dimnames=list(genes,meta$PATNO));rm(v)
stopifnot(all(colSums(cts)==meta$library_total))
meta$group <- factor(meta$group,levels=c('Control','PD'));rownames(meta)<-meta$PATNO
stopifnot(min(table(meta$group))>=2,all(meta$label==as.integer(meta$group=='PD')))
keep <- rowSums(cts>=10)>=min(table(meta$group))
write.table(data.frame(Geneid=genes,retained=keep),file.path(dest,'prefilter.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
stopifnot(sum(keep)>0,qr(model.matrix(~group,meta))$rank==2)
dds <- DESeqDataSetFromMatrix(cts[keep,,drop=FALSE],meta,~group)
dds <- DESeq(dds,test='Wald',fitType='parametric',sfType='ratio',betaPrior=FALSE,minReplicatesForReplace=Inf,parallel=FALSE)
bad <- which(!mcols(dds)$betaConv)
if(length(bad)) dds[bad,] <- nbinomWaldTest(dds[bad,],betaPrior=FALSE,maxit=1000)
conv <- mcols(dds)$betaConv
stopifnot(any(conv))
res <- results(dds,name='group_PD_vs_Control',alpha=.05,independentFiltering=FALSE)
res[,] <- NA_real_
good <- results(dds[conv,],name='group_PD_vs_Control',alpha=.05,independentFiltering=TRUE,pAdjustMethod='BH')
res[conv,] <- good
res$baseMean <- mcols(dds)$baseMean
tab <- data.frame(Geneid=rownames(dds),as.data.frame(res),beta_converged=conv,dispersion=dispersions(dds))
out <- gzfile(file.path(dest,'de_results.tsv.gz'),'wt')
write.table(tab,out,sep='\t',quote=FALSE,row.names=FALSE);close(out)
selected <- with(tab,beta_converged & is.finite(stat) & is.finite(pvalue) & is.finite(padj) & is.finite(log2FoldChange) & padj<.05 & abs(log2FoldChange)>.5)
write.table(tab[selected,],file.path(dest,'selected_genes.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
write.table(data.frame(PATNO=meta$PATNO,size_factor=sizeFactors(dds)),file.path(dest,'size_factors.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
capture.output(sessionInfo(),file=file.path(dest,'sessionInfo.txt'))
write_json(list(status='COMPLETE',training_n=nrow(meta),PD=sum(meta$group=='PD'),Control=sum(meta$group=='Control'),prefiltered=sum(keep),selected=sum(selected),initial_nonconverged=length(bad),persistent_nonconverged=sum(!conv),design='~ group',dispersion_fit=attr(dispersionFunction(dds),'fitType'),independent_filter_threshold=metadata(good)$filterThreshold,seconds=as.numeric(difftime(Sys.time(),started,units='secs'))),file.path(dest,'complete.json'),pretty=TRUE,auto_unbox=TRUE)
